language: php

php:
    - 7.4
    - 8.0

before_install:
    - echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
    - composer self-update
    - composer --version
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then wget https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php php-cs-fixer.phar --version; fi

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then php php-cs-fixer.phar fix src --rules=@Symfony --dry-run -v; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then bin/phpunit --coverage-clover build/logs/clover.xml; else bin/phpunit; fi

after_script:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.4" ]]; then php php-coveralls.phar -v; fi;
